variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 8
  GIT_DEPTH: "5"
  DOCKER_TLS_CERTDIR: "/certs"
before_script:
  - export GRADLE_USER_HOME=`pwd`/.ghome
  - export ROOT=`pwd`

stages:
  - validate
  - cleanup
  - deploy

gradle-compile:
  image: java11
  stage: validate
  cache:
      key: blazecore
      paths:
          - .gradle/
          - .ghome/
          - build/fg_cache/
  script:
    - export GRADLE_OPTS="-Xmx4G -Xms4G"
    - ./gradlew compileJava

cleanup:
  image: docker:20.10.16
  stage: cleanup
  when: always
  before_script:
    - ''
  dependencies:
    - gradle-compile
  tags:
    - edge
  script:
    - docker ps -a -q -f status=exited | xargs --no-run-if-empty docker rm -v
    - docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi

gradle-build:
    image: java11
    stage: deploy
    cache:
        key: blazecore
        paths:
          - .gradle/
          - .ghome/
          - build/fg_cache/
    dependencies:
        - gradle-compile
    when: manual
    script:
        - export GRADLE_OPTS="-Xmx4G -Xms4G"
        - ./gradlew build
    artifacts:
        paths:
            - build/libs/*-universal.jar
            - build/libs/*-server.jar
        expire_in: 1 days
